config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-crimson-flamingo.sh
        container: qc.acc_seedy-pumpkin-squirrel
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-thistle-guppy.sh
        container: qc.doc_cranky-tangerine-leopard
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-periwinkle-millipede.sh
        container: qc.doc_cloudy-magnolia-pig
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-scarlet-squirrel.sh
        container: qc.doc_skinny-bistre-cockroach
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-dandelion-eagle.sh
        container: qc.doc_slimy-chocolate-snail
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-brass-turkey.sh
        container: qc.lic_blurry-mustard-cat
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-tomato-hyena.sh
        container: qc.sec_shabby-chocolate-malamute
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-purple-horse.sh
        container: qc.sty_wiggy-tan-macaque
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-silver-duck.sh
        container: qc.sty_whiny-periwinkle-wrasse
      github.com/EOSC-synergy/FAIR_eva stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-orchid-fish.sh
        container: qc.sty_gamy-thistle-gerbil
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-linen-crab.sh
        container: qc.ver_squirrely-firebrick-warthog
timeout: 1800
