config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-tan-sheepdog.sh
        container: qc.acc_trippy-firebrick-ocelot
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-mustard-buzzard.sh
        container: qc.doc_chummy-smalt-snail
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cyan-slug.sh
        container: qc.doc_ready-russet-bobcat
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-aqua-paradise.sh
        container: qc.doc_leaky-corn-cichlid
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-flax-rat.sh
        container: qc.doc_flaky-sangria-setter
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-chocolate-toucan.sh
        container: qc.lic_scanty-plum-wrasse
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-pear-kakapo.sh
        container: qc.sec_stuffy-asparagus-gopher
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-crimson-wallaby.sh
        container: qc.sty_tasty-sepia-balinese
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cyan-retriever.sh
        container: qc.sty_grumpy-red-caiman
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-apricot-elephant.sh
        container: qc.ver_slimy-indigo-bongo
timeout: 1800
