config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-buff-wombat.sh
        container: qc.acc_ready-corn-ocelot
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-teal-mole.sh
        container: qc.doc_cranky-wisteria-turtle
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-olive-dodo.sh
        container: qc.doc_flabby-heliotrope-kakapo
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-maroon-oriole.sh
        container: qc.doc_lousy-orange-turtle
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-taupe-rat.sh
        container: qc.doc_smelly-rust-corgi
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/FAIR_eva F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-ecru-warthog.sh
        container: qc.fair_skimpy-russet-rottweiler
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cardinal-bat.sh
        container: qc.lic_gloppy-brass-wolverine
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-blue-rat.sh
        container: qc.sec_thirsty-red-ant
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-vermilion-raccoon.sh
        container: qc.sty_bluesy-cardinal-budgerigar
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-eggplant-iguana.sh
        container: qc.ver_hazy-aqua-horse
timeout: 1800
