config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-xanthic-booby.sh
        container: qc.acc_ugly-dandelion-hound
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-lemon-kiwi.sh
        container: qc.doc_slaphappy-ultramarine-civet
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-plum-robin.sh
        container: qc.doc_lumpy-fuchsia-sponge
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-black-lionfish.sh
        container: qc.doc_seedy-rust-spoonbill
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-cyan-cattle.sh
        container: qc.doc_shaky-indigo-turkey
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-purple-jackal.sh
        container: qc.lic_tasty-lilac-rhinoceros
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-aqua-mule.sh
        container: qc.sec_blurry-chocolate-tarsier
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-sepia-shark.sh
        container: qc.sty_clammy-maroon-chamois
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-brass-mule.sh
        container: qc.sty_sleazy-cardinal-mule
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-tan-neanderthal.sh
        container: qc.ver_snappy-plum-hummingbird
timeout: 1800
