config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.6.0-no_svcqa
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-apricot-jaguar.sh
        container: qc.acc_queasy-red-bandicoot
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-green-labradoodle.sh
        container: qc.doc_gloppy-periwinkle-quail
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-brown-barb.sh
        container: qc.doc_snoopy-purple-mole
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-ivory-pinscher.sh
        container: qc.doc_pasty-taupe-caracal
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-bistre-dachshund.sh
        container: qc.lic_sleazy-olivine-llama
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cream-oriole.sh
        container: qc.sec_surly-vermilion-zonkey
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cerulean-cuscus.sh
        container: qc.sty_beady-ecru-seahorse
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-flax-warthog.sh
        container: qc.ver_gloppy-platinum-koala
timeout: 600
