config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-wisteria-oyster.sh
        container: qc.acc_muzzy-cinnabar-antelope
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-aquamarine-eel.sh
        container: qc.doc_surly-seashell-flamingo
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-viridian-bobcat.sh
        container: qc.doc_pretty-periwinkle-russel
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-salmon-blue.sh
        container: qc.doc_shaggy-amber-capybara
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-mauve-barnacle.sh
        container: qc.doc_wiggy-tangerine-burmese
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/FAIR_eva F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-brass-balinese.sh
        container: qc.fair_gummy-charcoal-dolphin
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-firebrick-vulture.sh
        container: qc.lic_skanky-zucchini-mist
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-olivine-mongoose.sh
        container: qc.sec_blurry-lavender-eel
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-sapphire-cockroach.sh
        container: qc.sty_craggy-chestnut-frigatebird
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-bronze-fossa.sh
        container: qc.ver_snappy-dandelion-alligator
timeout: 1800
