config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-flax-lemur.sh
        container: qc.acc_breezy-carmine-lionfish
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-platinum-mongoose.sh
        container: qc.doc_sickly-cerise-harrier
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-ochre-dolphin.sh
        container: qc.doc_muzzy-chestnut-mau
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-zucchini-giraffe.sh
        container: qc.doc_randy-goldenrod-beetle
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-malachite-labradoodle.sh
        container: qc.doc_muzzy-vermilion-quetzal
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-green-tiger.sh
        container: qc.lic_muggy-azure-shrew
  QC.Met:
    repos:
      github.com/EOSC-synergy/FAIR_eva cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-wheat-binturong.sh
        container: qc.met_woozy-burgundy-raccoon
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-champagne-spaniel.sh
        container: qc.sec_surly-dandelion-turtle
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-rose-sheepdog.sh
        container: qc.sty_hasty-bistre-clam
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-saffron-swan.sh
        container: qc.sty_trippy-champagne-bear
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-lavender-seahorse.sh
        container: qc.ver_flimsy-bistre-tiger
timeout: 1800
