config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-celadon-baboon.sh
        container: qc.acc_scaly-maroon-spider
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-bistre-mayfly.sh
        container: qc.doc_scaly-red-cheetah
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-tangerine-wasp.sh
        container: qc.doc_sleepy-cardinal-axolotl
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cyan-bordeaux.sh
        container: qc.doc_gimpy-seashell-jellyfish
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-linen-monster.sh
        container: qc.doc_woozy-myrtle-quoll
  QC.FAIR:
    repos:
      github.com/EOSC-synergy/FAIR_eva F-UJI:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-russet-chow.sh
        container: qc.fair_snoopy-orange-llama
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-chartreuse-cuscus.sh
        container: qc.lic_freaky-tan-leopard
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-taupe-forest.sh
        container: qc.sec_woolly-tangerine-starfish
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-eggplant-molly.sh
        container: qc.sty_skimpy-mauve-quetzal
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-sangria-mole.sh
        container: qc.ver_flabby-tangerine-maltese
timeout: 1800
