config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-chartreuse-chihuahua.sh
        container: qc.acc_gimpy-cobalt-ferret
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-copper-mouse.sh
        container: qc.doc_homely-indigo-olm
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-lavender-tetra.sh
        container: qc.doc_snippy-harlequin-gecko
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-olivine-seahorse.sh
        container: qc.doc_gamy-black-zebra
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-gold-crab.sh
        container: qc.doc_hasty-orange-gerbil
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-ecru-manatee.sh
        container: qc.lic_sickly-lemon-wombat
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-ochre-squid.sh
        container: qc.sec_woolly-peach-chipmunk
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-wheat-squirrel.sh
        container: qc.sty_ugly-pear-octopus
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cream-dogfish.sh
        container: qc.sty_slaphappy-gold-warthog
      github.com/EOSC-synergy/FAIR_eva stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-flax-fish.sh
        container: qc.sty_shaggy-wisteria-fossa
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-black-fossa.sh
        container: qc.ver_chummy-burgundy-wolfhound
timeout: 1800
