config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-turquoise-nightingale.sh
        container: qc.acc_squeaky-sapphire-tzu
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-yellow-lion.sh
        container: qc.doc_greasy-purple-retriever
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-charcoal-moorhen.sh
        container: qc.doc_nerdy-ivory-kangaroo
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-white-chimpanzee.sh
        container: qc.doc_seedy-linen-civet
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chartreuse-barracuda.sh
        container: qc.doc_wiggy-gamboge-ferret
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cerulean-okapi.sh
        container: qc.lic_tacky-cobalt-baboon
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-ultramarine-tapir.sh
        container: qc.sec_geeky-dandelion-octopus
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-heliotrope-greyhound.sh
        container: qc.sty_sickly-wheat-badger
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-razzmatazz-mist.sh
        container: qc.sty_scummy-denim-audemer
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-flax-chinchilla.sh
        container: qc.ver_jumpy-platinum-insect
timeout: 1800
