config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/FAIR_eva:
      branch: main
      repo: https://github.com/EOSC-synergy/FAIR_eva
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-scarlet-mole.sh
        container: qc.acc_freaky-linen-gibbon
  QC.Doc:
    repos:
      github.com/EOSC-synergy/FAIR_eva find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-ivory-hummingbird.sh
        container: qc.doc_hilly-blue-vulture
      github.com/EOSC-synergy/FAIR_eva git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-wisteria-devil.sh
        container: qc.doc_bluesy-pear-anteater
      github.com/EOSC-synergy/FAIR_eva markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-tan-alligator.sh
        container: qc.doc_homely-seashell-hamster
      github.com/EOSC-synergy/FAIR_eva restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ecru-mist.sh
        container: qc.doc_shaggy-harlequin-chihuahua
  QC.Lic:
    repos:
      github.com/EOSC-synergy/FAIR_eva licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-seashell-havanese.sh
        container: qc.lic_stuffy-tangerine-dachshund
  QC.Sec:
    repos:
      github.com/EOSC-synergy/FAIR_eva bandit:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-magnolia-chinchilla.sh
        container: qc.sec_freaky-pear-eagle
  QC.Sty:
    repos:
      github.com/EOSC-synergy/FAIR_eva flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cinnabar-serval.sh
        container: qc.sty_pasty-goldenrod-dodo
      github.com/EOSC-synergy/FAIR_eva hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-bronze-tiger.sh
        container: qc.sty_pokey-apricot-octopus
  QC.Ver:
    repos:
      github.com/EOSC-synergy/FAIR_eva get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-yellow-moorhen.sh
        container: qc.ver_muzzy-auburn-zebra
timeout: 1800
